image:
    file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
    - port: 3000
      onOpen: open-preview
    - port: 3001
      onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
    - command: >
          nvm install 15 &&
          nvm alias default 15 &&
          npm install pnpm -g &&
          pnpm install gulp ultra-runner commitizen -g  &&
          pnpm update &&
          pnpm build &&
          pnpm demo
