[build]
    command = "set -xeuo pipefail && (test "$CI" = true || exit 1) && npx pnpm install -r --store-dir=node_modules/.pnpm-store && pnpm docs"
[build.environment]
    NPM_FLAGS="--prefix=./bin/empty-project/"