image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-browser
  - port: 3001
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - command: >
      ultra build &&
      ultra test:watch

vscode:
  extensions:
    - vivaxy.vscode-conventional-commits@1.13.0:zCJe2ITK+hf+3DCumvNLfA==
